
name: 'build'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'my token'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}